version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    image: jrtec/fastapi-alembic-sqlmodel-async:latest
    restart: always
    command: "sh -c 'alembic upgrade head && python app/initial_data.py && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    env_file: ".env"
    depends_on:
      - database
      - redis_server
    links:
      - caddy_reverse_proxy:storage.localhost
  
  ## You need to set your external database credentials in .env file or uncomment below lines to run database as container  (No recommended because db needs persitence)
  # database:
  #   image: bitnami/postgresql
  #   restart: always
  #   container_name: database
  #   env_file: ".env"
  #   user: root
  #   volumes:
  #     - db_docker:/bitnami/postgresql
  #     - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
  #   ports:
  #     - 5454:5432 # Remove this on production
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRESQL_USERNAME=${DATABASE_USER}
  #     - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRESQL_DATABASE=${DATABASE_NAME}

      
  caddy_reverse_proxy:
    container_name: caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80      
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/code/static
      - caddy_data:/data
      - caddy_config:/config

  redis_server:
    container_name: redis_server
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    env_file: .env

  frontend:
    container_name: frontend
    build: ./frontend
    command: npm run preview -- --host --port 5173
    restart: always
    env_file: .env
    expose:
      - 5173
    depends_on:
      - fastapi_server

volumes:
  caddy_data:
  caddy_config:
