version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    build: 
      context: ./backend      
      args:
        INSTALL_DEV: "true"
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    env_file: ".env"
    environment:                
      MODE: "testing"      
    depends_on:
      - database
      - redis_server
    links:
      - caddy_reverse_proxy:storage.localhost

  database:
    image: bitnami/postgresql
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - db_docker:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - 5454:5432 # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}

  redis_server:
    image: redis:alpine
    container_name: redis_server    
    restart: always
    expose:
      - 6379
    env_file: .env

  caddy_reverse_proxy:
    container_name: caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80      
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/code/static
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: npm run dev -- --host --port 5173
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file: .env
    expose:
      - 5173
    depends_on:
      - fastapi_server

volumes:
  db_docker:
  caddy_data:
  caddy_config:
